# Noctalia v5 User-defined templates

[theme.templates.user.gtk3]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/gtk3.css"
output_path = '$XDG_CONFIG_HOME/gtk-3.0/gtk.css'

[theme.templates.user.gtk4]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/gtk4.css"
output_path = '$XDG_CONFIG_HOME/gtk-4.0/gtk.css'

[theme.templates.user.hyprland]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/hyprland.conf"
output_path = "$XDG_CONFIG_HOME/hypr/noctalia/noctalia-overrides.conf"

[theme.templates.user.discordCustomVesktop]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/discord-midnight.css"
output_path = "$XDG_CONFIG_HOME/vesktop/themes/discord-midnight-alt.css"

[theme.templates.user.discordCustomFlatpakVencord]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/discord-midnight.css"
output_path = "$HOME/.var/app/com.discordapp.Discord/config/Vencord/themes/noctalia-midnight-alt.css"

[theme.templates.user.overview]
input_path = "$XDG_CONFIG_HOME/noctalia/matugenTemplates/quickshell-overview.qml"
output_path = "$XDG_CONFIG_HOME/quickshell/overview/common/Appearance.colors.qml"
