general {
    col.active_border = rgba(5f3f3aAA)
    col.inactive_border = rgba(2a1614FF)
}

misc {
    background_color = rgba(200e0cFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(200e0cFF)
        col.text = rgba(ffdad5FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ffdad5), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(ffdad5), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(ffdad5), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule = border_color rgba(ffb4aaAA) rgba(ffb4aa77), match:pin 1
