$primary = rgb(b8d06e)
$surface = rgb(13140e)
$secondary = rgb(c1cb9d)
$error = rgb(ffb4ab)
$tertiary = rgb(80d9a2)
$surface_lowest = rgb(0d0f09)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
