color0 #0e1513
color1 #ffb4ab
color2 #2fdec1
color3 #9bd1c3
color4 #c7bfff
color5 #2fdec1
color6 #9bd1c3
color7 #dce4e0
color8 #85948f
color9 #ffb4ab
color10 #2fdec1
color11 #9bd1c3
color12 #c7bfff
color13 #2fdec1
color14 #9bd1c3
color15 #dce4e0

cursor                #dce4e0
cursor_text_color     #0e1513
background            #0e1513
foreground            #dce4e0
selection_foreground  #bacac4
selection_background  #3b4a46
active_border_color   #2fdec1
inactive_border_color #3b4a46
url_color             #2fdec1

active_tab_foreground   #00382f
active_tab_background   #2fdec1
inactive_tab_foreground #bacac4
inactive_tab_background #3b4a46
cursor_trail_color      #bacac4
