color0 #131313
color1 #ffb4ab
color2 #a5d576
color3 #bfcbad
color4 #a0cfcd
color5 #a5d576
color6 #bfcbad
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #a5d576
color11 #bfcbad
color12 #a0cfcd
color13 #a5d576
color14 #bfcbad
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #a5d576
inactive_border_color #474747
url_color             #a5d576

active_tab_foreground   #1c3700
active_tab_background   #a5d576
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
