color0 #131313
color1 #ffb4ab
color2 #91d888
color3 #baccb3
color4 #a0cfd3
color5 #91d888
color6 #baccb3
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #91d888
color11 #baccb3
color12 #a0cfd3
color13 #91d888
color14 #baccb3
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #91d888
inactive_border_color #474747
url_color             #91d888

active_tab_foreground   #003907
active_tab_background   #91d888
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
